In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


# For feature selection

from sklearn.linear_model import Lasso
from sklearn.feature_selection import SelectFromModel

In [2]:
df = pd.read_csv('After_preprocessing.csv')

In [3]:
df.shape

(1460, 84)

In [4]:
df.head()

Id  SalePrice  MSSubClass  MSZoning  LotFrontage   LotArea  Street  Alley  \
0   1  12.247694    0.235294      0.75     0.418208  0.366344     1.0    0.5   
1   2  12.109011    0.000000      0.75     0.495064  0.391317     1.0    0.5   
2   3  12.317167    0.235294      0.75     0.434909  0.422359     1.0    0.5   
3   4  11.849398    0.294118      0.75     0.388581  0.390295     1.0    0.5   
4   5  12.429216    0.235294      0.75     0.513123  0.468761     1.0    0.5   

   LotShape  LandContour  ...  Fence  MiscFeature  MiscVal    MoSold  YrSold  \
0       1.0          1.0  ...    0.5         0.25      0.0  0.090909    0.50   
1       1.0          1.0  ...    0.5         0.25      0.0  0.363636    0.25   
2       0.0          1.0  ...    0.5         0.25      0.0  0.727273    0.50   
3       0.0          1.0  ...    0.5         0.25      0.0  0.090909    0.00   
4       0.0          1.0  ...    0.5         0.25      0.0  1.000000    0.50   

   SaleType  SaleCondition  LotFrontage_NAN  MasVnrArea_NAN  GarageYrBlt_NAN  
0       1.0            0.8              0.0             0.0              0.0  
1       1.0            0.8              0.0             0.0              0.0  
2       1.0            0.8              0.0             0.0              0.0  
3       1.0            0.0              0.0             0.0              0.0  
4       1.0            0.8              0.0             0.0              0.0  

[5 rows x 84 columns]

In [5]:
y = df[['SalePrice']]

In [6]:
x = df.drop(['Id','SalePrice'],axis=1)

In [92]:
#first apply lasso to et alpha value, the higher the value of alpha lesser the no of features selected
feature_select_model = SelectFromModel(Lasso(alpha=0.003,random_state=0))
feature_select_model.fit(x,y)

SelectFromModel(estimator=Lasso(alpha=0.003, copy_X=True, fit_intercept=True,
                                max_iter=1000, normalize=False, positive=False,
                                precompute=False, random_state=0,
                                selection='cyclic', tol=0.0001,
                                warm_start=False),
                max_features=None, norm_order=1, prefit=False, threshold=None)

In [93]:
feature_select_model.get_support()

array([False, False, False,  True, False, False,  True, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True, False, False, False, False, False, False,  True,
       False, False,  True,  True,  True,  True, False, False, False,
       False, False, False,  True,  True, False,  True, False, False,
        True,  True, False,  True,  True, False, False,  True, False,
        True,  True, False,  True, False,  True,  True, False, False,
       False,  True, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True, False, False,
       False])

In [94]:
selected_features = x.columns[(feature_select_model.get_support())]
print('Total features:',x.shape[1])
print('Selected features :',len(selected_features))

Total features: 82
Selected features : 27


In [95]:
selected_features
#These are important features

Index(['LotArea', 'LotShape', 'BldgType', 'OverallQual', 'OverallCond',
       'YearBuilt', 'YearRemodAdd', 'ExterQual', 'BsmtQual', 'BsmtCond',
       'BsmtExposure', 'BsmtFinType1', 'HeatingQC', 'CentralAir', '1stFlrSF',
       'GrLivArea', 'BsmtFullBath', 'FullBath', 'HalfBath', 'KitchenQual',
       'Functional', 'Fireplaces', 'GarageType', 'GarageFinish', 'GarageCars',
       'PavedDrive', 'SaleCondition'],
      dtype='object')

In [96]:
new_x = x[selected_features]
new_x.head()

LotArea  LotShape  BldgType  OverallQual  OverallCond  YearBuilt  \
0  0.366344       1.0       0.0     0.666667        0.500   0.036765   
1  0.391317       1.0       0.0     0.555556        0.875   0.227941   
2  0.422359       0.0       0.0     0.666667        0.500   0.051471   
3  0.390295       0.0       0.0     0.666667        0.500   0.669118   
4  0.468761       0.0       0.0     0.777778        0.500   0.058824   

   YearRemodAdd  ExterQual  BsmtQual  BsmtCond  ...  FullBath  HalfBath  \
0      0.098361   0.666667       0.5      1.00  ...  0.666667       0.5   
1      0.524590   1.000000       0.5      1.00  ...  0.666667       0.0   
2      0.114754   0.666667       0.5      1.00  ...  0.666667       0.5   
3      0.606557   1.000000       1.0      0.25  ...  0.333333       0.0   
4      0.147541   0.666667       0.5      1.00  ...  0.666667       0.5   

   KitchenQual  Functional  Fireplaces  GarageType  GarageFinish  GarageCars  \
0     0.666667         1.0    0.000000    0.166667      0.666667        0.50   
1     1.000000         1.0    0.333333    0.166667      0.666667        0.50   
2     0.666667         1.0    0.333333    0.166667      0.666667        0.50   
3     0.666667         1.0    0.333333    0.833333      1.000000        0.75   
4     0.666667         1.0    0.333333    0.166667      0.666667        0.75   

   PavedDrive  SaleCondition  
0         1.0            0.8  
1         1.0            0.8  
2         1.0            0.8  
3         1.0            0.0  
4         1.0            0.8  

[5 rows x 27 columns]

In [99]:
from sklearn.model_selection import train_test_split
#first with all features
x_train,x_test,y_train,y_test = train_test_split(new_x,y.values,test_size = 0.2,random_state=42)

In [62]:
from sklearn.linear_model import LinearRegression
model1 = LinearRegression()
model1.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [63]:
pred = model1.predict(x_test)

In [64]:
from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,pred)

0.018935891668794485

In [65]:
pred_log_inverse = np.exp(pred)
actual_log_inverse = np.exp(y_test)

In [66]:
mean_squared_error(actual_log_inverse,pred_log_inverse)

1100558822.4445722

In [67]:
pred_log_inverse[1]

array([326538.79391115])

In [68]:
actual_log_inverse[1]

array([325000.])

In [69]:
testing_data = pd.read_csv('After_preprocessing_test.csv')

In [70]:
x_testing_data = testing_data[selected_features]
x_testing_data

LotShape  BldgType  OverallQual  YearBuilt  YearRemodAdd  ExterQual  \
0          1.0      0.00     0.444444   0.384615      0.822581   1.000000   
1          0.0      0.00     0.555556   0.407692      0.870968   1.000000   
2          0.0      0.00     0.444444   0.107692      0.225806   1.000000   
3          0.0      0.00     0.555556   0.100000      0.225806   1.000000   
4          0.0      1.00     0.777778   0.146154      0.322581   0.666667   
...        ...       ...          ...        ...           ...        ...   
1454       1.0      0.75     0.333333   0.284615      0.612903   1.000000   
1455       1.0      1.00     0.333333   0.284615      0.612903   1.000000   
1456       1.0      0.00     0.444444   0.361538      0.193548   1.000000   
1457       1.0      0.00     0.444444   0.115385      0.258065   1.000000   
1458       1.0      0.00     0.666667   0.107692      0.225806   1.000000   

      BsmtQual  BsmtExposure  BsmtFinType1  HeatingQC  ...  1stFlrSF  \
0          1.0           1.0      0.833333        1.0  ...  0.312253   
1          1.0           1.0      0.000000        1.0  ...  0.468253   
2          0.5           1.0      0.333333        0.5  ...  0.326139   
3          1.0           1.0      0.333333        0.0  ...  0.325285   
4          0.5           1.0      0.000000        0.0  ...  0.453388   
...        ...           ...           ...        ...  ...       ...   
1454       1.0           1.0      1.000000        0.5  ...  0.116257   
1455       1.0           1.0      0.833333        1.0  ...  0.116257   
1456       1.0           1.0      0.000000        0.0  ...  0.435686   
1457       0.5           0.0      0.333333        1.0  ...  0.343654   
1458       0.5           0.0      0.500000        0.0  ...  0.354121   

      GrLivArea  BsmtFullBath  KitchenQual  Fireplaces  GarageType  \
0      0.312253      0.000000          1.0        0.00    0.166667   
1      0.468253      0.000000          0.5        0.00    0.166667   
2      0.548792      0.000000          1.0        0.25    0.166667   
3      0.542672      0.000000          0.5        0.25    0.166667   
4      0.453388      0.000000          0.5        0.00    0.166667   
...         ...           ...          ...         ...         ...   
1454   0.390532      0.000000          1.0        0.00    1.000000   
1455   0.390532      0.000000          1.0        0.00    0.666667   
1456   0.435686      0.333333          1.0        0.25    0.833333   
1457   0.343654      0.000000          1.0        0.00    1.000000   
1458   0.629981      0.000000          1.0        0.25    0.166667   

      GarageFinish  GarageCars  PavedDrive  SaleCondition  
0         1.000000         0.2         1.0            0.8  
1         1.000000         0.2         1.0            0.8  
2         0.000000         0.4         1.0            0.8  
3         0.000000         0.4         1.0            0.8  
4         0.666667         0.4         1.0            0.8  
...            ...         ...         ...            ...  
1454      0.333333         0.0         1.0            0.8  
1455      1.000000         0.2         1.0            0.0  
1456      1.000000         0.4         1.0            0.0  
1457      0.333333         0.0         1.0            0.8  
1458      0.000000         0.6         1.0            0.8  

[1459 rows x 21 columns]

In [71]:
predicted_y1 = model1.predict(x_testing_data)

In [72]:
predicted_y1 = np.exp(predicted_y1)

In [73]:
predicted_y1

array([[ 96371.38556726],
       [144092.30182389],
       [161304.57489934],
       ...,
       [133968.34260763],
       [112097.62918068],
       [218903.46341613]])

In [74]:
predicted_y1 = predicted_y1.flatten()

In [75]:
submission = pd.DataFrame({"SalePrice": predicted_y1})
submission.index.name = 'Id'
submission.index+=1461

In [76]:
submission

SalePrice
Id                 
1461   96371.385567
1462  144092.301824
1463  161304.574899
1464  178704.966891
1465  179951.375358
...             ...
2915   81654.697628
2916   76527.201831
2917  133968.342608
2918  112097.629181
2919  218903.463416

[1459 rows x 1 columns]

In [77]:
submission.to_csv("submission1.csv")

In [81]:
# With Ridge cross validation
from sklearn.linear_model import RidgeCV
reg = RidgeCV(alphas=[1, 1e3, 1e6], store_cv_values=True)
reg.fit(x_train,y_train)
cv_mse = np.mean(reg.cv_values_,axis=0)

print(cv_mse)


[[0.02142511 0.09098192 0.15548686]]


In [82]:
print(reg.alpha_)

1.0


In [87]:
y_predict = reg.predict(x_test)
mean_squared_error(y_test,y_predict)

0.019156067148756617

In [88]:
predicted_y1 = reg.predict(x_testing_data)
predicted_y1 = np.exp(predicted_y1)
predicted_y1 = predicted_y1.flatten()
submission = pd.DataFrame({"SalePrice": predicted_y1})
submission.index.name = 'Id'
submission.index+=1461
submission.to_csv("submission1.csv")